[package]
name = "litrs"
version = "0.1.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
edition = "2018"

[features]
default = ["proc-macro", "proc-macro2"]
proc-macro = []

[dependencies]
proc-macro2 = { version = "1", optional = true }
