name: CI

on:
  pull_request:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  check:
    name: 'Build & test'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    # We build and test in release mode as one test would take a long time
    # otherwise.
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release -- --include-ignored
