name: CI

on:
  pull_request:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  check:
    name: 'Build & test'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    # We test in release mode as two tests would take a long time otherwise.
    - name: Build
      run: cargo build
    - name: Run tests
      run: |
        cargo test --release --lib -- --include-ignored
        cargo test --doc
    - name: Test procmacro example
      working-directory: examples/procmacro
      run: cargo test

    - name: Build without default features
      run: cargo build --no-default-features
    - name: Run tests without default features
      run: |
        cargo test --release --no-default-features --lib -- --include-ignored
        cargo test --doc --no-default-features
